### ISSUE TITLE
`kmeans_init` documentation

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/kmeans_R#28]
It would be helpful for the user if you fleshed out your documentation for the `algorithm` argument of the `kmeans_init` function. It is nice if you list the examples of strings that would work with your function (don't make the user guess). You give one example, `algorithm = "kmeans++"` , which is the default. But what other options will work with your function? If none, then why have this as an option.

**Comment by johannesharmse** [comment]
Thanks for the feedback.

The scope of the initial package was to only include "kmeans++", given its reliable initialization. However, it seems logical to at least include the random points method as well, which will have a performance advantage over kmeans++ for larger datasets. A new algorithm "rp" (random points) has been developed and is passing all current tests, but still has to be reviewed before the next release.

This issue will remain open until it has been reviewed and merged with the master branch.

Additional Notes:

* It has been decided to change "kmeans++" to "kmeanspp", because it may cause regular expression issues on some machines. This will be merged into the master branch once approved by reviewers.

* The `algorithm` argument is being changed to `method`, given that it is a more generic umbrella term. This will be merged into the master branch once approved by reviewers.

**Comment by johannesharmse** [comment]
Changes have successfully been implemented.
